module "vpc" {
  source = "../terraform-vpc-module"
  cidr_ips = var.cidr_ips
  tenancy = var.tenancy
  project = var.project
  environment = var.environment
  vpc_tags = var.vpc_tags
  public-cidr-blocks = var.public-cidr-blocks
  private-cidr-blocks = var.private-cidr-blocks
  database-cidr-blocks = var.database-cidr-blocks
  vpc_pub_subnet_tags = var.vpc_pub_subnet_tags
  vpc_priv_subnet_tags = var.vpc_priv_subnet_tags
  vpc_db_subnet_tags = var.vpc_db_subnet_tags
  igw_tags = var.igw_tags
  public_rt_tags = var.public_rt_tags
  private_rt_tags = var.private_rt_tags
  database_rt_tags = var.database_rt_tags
  eip_tags = var.eip_tags
  nat_gateway_tags = var.nat_gateway_tags
  dest-cidr = var.dest-cidr
}
