- name: configure payment server
  hosts: payment
  become: yes
  tasks:
  - name: install python package
    dnf:
      name: "{{ item }}"
      state: present
    loop:
    - python3
    - gcc
    - python3-devel

  - name: create roboshop system user
    user:
      name: roboshop
      comment: RoboShop System user
      system: true
      shell: /sbin/nologin
      home: /app
  # Safe to remove directory, because 2nd time if we run it will download freshly. no error if does not exist
  - name: remove app directory
    file:
      path: /app
      state: absent

  - name: create app directory
    file:
      state: directory
      path: /app

  - name: Delete payment file
    file:
      path: /tmp/payment.zip
      state: absent

  - name: download payment application
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip

  - name: extract payment application
    unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: copy payment service
    copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: daemon reload enable and start
    systemd_service:
      name: payment
      enabled: true
      state: started
      daemon_reload: true