- name: setup redis server
  hosts: redis
  tasks:
  - name: disable default redis
    command: dnf module disable redis -y

  - name: enable redis 7
    command: dnf module enable redis:7 -y

  - name: install redis
    dnf:
      name: redis
      state: present
  
  - name: allow remote connections
    replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: disable proctected mode
    lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: 'protected-mode no'

  - name: start and enable redis
    service:
      name: redis
      enabled: yes
      state: started