  - name: create roboshop system user
    user:
      name: roboshop
      comment: RoboShop System user
      system: true
      shell: /sbin/nologin
      home: /app
  
  - name: remove app directory
    file:
      path: /app
      state: absent

  - name: create app directory
    file:
      state: directory
      path: /app

  - name: "Delete {{ component }} file"
    file:
      path: "/tmp/{{ component }}.zip"
      state: absent

  - name: "download {{ component }} application"
    get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip"
      dest: "/tmp/{{ component }}.zip"
  
  - name: "extract {{ component }} application"
    unarchive:
      src: "/tmp/{{ component }}.zip"
      dest: /app
      remote_src: yes