  - name: disable default nodejs
    command: dnf module disable nodejs -y

  - name: enable nodejs 20
    command: dnf module enable nodejs:20 -y

  - name: install nodejs
    dnf:
      name: nodejs
      state: present

  - name: install dependencies
    npm:
      path: /app