- name: "setup  {{ component }} server"
  hosts: " {{ component }}"
  become: yes
  delegate_to: localhost
  roles:
  - " {{ component }}"
  
  #ansible-playbook -i inventory main.yaml -e "component=mysql"
